---
version: '3.7'

services:
    thredds-production:
        image: unidata/thredds-docker:latest
        ports:
            - "80:8080"
            - "443:8443"
            - "8443:8443"
        container_name: thredds
        volumes:
            # LINK CONFIGS (make them read only to be easier to edit on host)
            - type: bind
              source: ./threddsConfig.xml
              target: /usr/local/tomcat/content/thredds/threddsConfig.xml
              read_only: true

            # - type: bind
            #   source: ./thredds/catalog.xml
            #   target: /usr/local/tomcat/content/thredds/catalog.xml
            #   read_only: true

            # - type: bind
            #   source: ./thredds/enhancedCatalog.xml
            #   target: /usr/local/tomcat/content/thredds/enhancedCatalog.xml
            #   read_only: true

            # - type: bind
            #   source: ./thredds/wmsConfig.xml
            #   target: /usr/local/tomcat/content/thredds/wmsConfig.xml
            #   read_only: true

            - type: bind
              source: ./tomcat-users.xml
              target: /usr/local/tomcat/conf/tomcat-users.xml
              read_only: true

              #THREADS FOLDER -- UNCOMMENT JUST IN CASE
            - type: bind
              source: ./thredds
              target: /usr/local/tomcat/content/thredds

              # ========================  LOGS
            - type: bind
              source: ./logs/tomcat/
              target: /usr/local/tomcat/logs/

            - type: bind
              source: ./logs/thredds/
              target: /usr/local/tomcat/content/thredds/logs/

              # ========================  DATA
            - type: bind
              source: /media/degas/model/ECMWF/ERA5/
              target: /usr/local/tomcat/content/thredds/public/ERA5/
              read_only: true

        env_file:
            - "compose${THREDDS_COMPOSE_ENV_LOCAL}.env"

####
## TDM - TODO Set this up
## https://github.com/Unidata/tdm-docker
####
#    tdm:
#        image: unidata/tdm-docker:latest
#        container_name: tdm
#        volumes:
#            - /path/to/your/thredds/directory:/usr/local/tomcat/content/thredds
#            - /path/to/your/data/directory1:/path/to/your/data/directory1
#              # TDM logging non-configurable until 5.0 so you'll need tdm.sh and
#              # tdm.jar if you want to log outside the container :-(
#            - /path/to/your/tdm/logs:/usr/local/tomcat/content/tdm/
#        env_file:
#            - "compose${THREDDS_COMPOSE_ENV_LOCAL}.env"

