---
version: '3.7'

services:
    thredds:
        image: unidata/thredds-docker:latest
        ports:
            - "80:8080"
            - "443:8443"
            - "8443:8443"
        container_name: thredds
        volumes:
            # LINK CONFIGS
            - type: bind # link threddsConfig separetly because the docker container changes permissions on this file inside /thredds
              source: ./threddsConfig.xml
              target: /usr/local/tomcat/content/thredds/threddsConfig.xml
              read_only: true 

            - type: bind
              source: ./tomcat-users.xml
              target: /usr/local/tomcat/conf/tomcat-users.xml
              read_only: true

              #THREADS FOLDER -- UNCOMMENT JUST IN CASE
            - type: bind
              source: ./thredds
              target: /usr/local/tomcat/content/thredds

              # ========================  LOGS
            - type: bind
              source: ./logs/tomcat/
              target: /usr/local/tomcat/logs/

            - type: bind
              source: ./logs/thredds/
              target: /usr/local/tomcat/content/thredds/logs/

              # ===============================================
              #                    DATA
              # ===============================================


              # =========================
              #         HINDCAST 
              # =========================
              #  ERA 5
            - type: bind
              source: /media/degas/model/ECMWF/ERA5/
              target: /usr/local/tomcat/content/thredds/public/data/hindcast/ERA5/
              read_only: true
              
              #  WAVERYS
            - type: bind
              source: /media/degas/model/WAVERYS/
              target: /usr/local/tomcat/content/thredds/public/data/hindcast/WAVERYS/
              read_only: true
              
              #  WAVERYS
            - type: bind
              source: /media/degas/model/IFREMER/
              target: /usr/local/tomcat/content/thredds/public/data/hindcast/IFREMER/
              read_only: true
              
              #  CFSR
            - type: bind
              source: /media/monet/public/model/hindcast/NCEP/atmos/CFSR/
              target: /usr/local/tomcat/content/thredds/public/data/hindcast/CFSR/
              read_only: true
              
              #  CFSv2
            - type: bind
              source: /media/monet/public/model/hindcast/NCEP/atmos/CFSv2/
              target: /usr/local/tomcat/content/thredds/public/data/hindcast/CFSv2/
              read_only: true

              #  WW3 ST4 - nopp2
            - type: bind
              source: /media/monet/public/model/hindcast/NCEP/wave/nopp-phase2/netcdf_subset/ # TODO -- This is temporary
              target: /usr/local/tomcat/content/thredds/public/data/hindcast/WW3ST4/
              read_only: true
              
              # =========================
              #         FORECAST
              # =========================
              
            - type: bind
              source: /media/monet/public/model/forecast/opftp/
              target: /usr/local/tomcat/content/thredds/public/data/forecast/
              read_only: true

            
        env_file:
            - "compose.env"

###
# TDM
# https://github.com/Unidata/tdm-docker
###
    tdm:
        image: unidata/tdm-docker:latest
        container_name: tdm
        volumes:
            - type: bind
              source: ./thredds
              target: /usr/local/tomcat/content/thredds

              # Bind this specifically because of permissions
            - type: bind
              source: ./threddsConfig.xml
              target: /usr/local/tomcat/content/thredds/threddsConfig.xml
              read_only: true

            - type: bind
              source: ./tdm/
              target: /usr/local/tomcat/content/tdm/

              # ========================  DATA

              # =========================
              #         HINDCAST 
              # =========================
              
              #  ERA 5
            - type: bind
              source: /media/degas/model/ECMWF/ERA5/
              target: /usr/local/tomcat/content/thredds/public/data/hindcast/ERA5/
              read_only: true
              
              #  WAVERYS
            - type: bind
              source: /media/degas/model/WAVERYS/
              target: /usr/local/tomcat/content/thredds/public/data/hindcast/WAVERYS/
              read_only: true
              
              #  WAVERYS
            - type: bind
              source: /media/degas/model/IFREMER/
              target: /usr/local/tomcat/content/thredds/public/data/hindcast/IFREMER/
              read_only: true
              
              #  CFSR
            - type: bind
              source: /media/monet/public/model/hindcast/NCEP/atmos/CFSR/
              target: /usr/local/tomcat/content/thredds/public/data/hindcast/CFSR/
              read_only: true
              
              #  CFSv2
            - type: bind
              source: /media/monet/public/model/hindcast/NCEP/atmos/CFSv2/
              target: /usr/local/tomcat/content/thredds/public/data/hindcast/CFSv2/
              read_only: true
              
              #  WW3 ST4 - nopp2
            - type: bind
              source: /media/monet/public/model/hindcast/NCEP/wave/nopp-phase2/netcdf_subset/
              target: /usr/local/tomcat/content/thredds/public/data/hindcast/WW3ST4/
              read_only: true
              
              # =========================
              #         FORECAST
              # =========================
              
            - type: bind
              source: /media/monet/public/model/forecast/opftp/
              target: /usr/local/tomcat/content/thredds/public/data/forecast/
              read_only: true
            
        env_file:
            - "compose.env"

